name: HCPowers
main: com.hcpowers.core.Core
author: Irantwomiles
description: Just desting
version: 1.0
commands:
  faction:
    description: faction commands
    aliases: [f, t, team]
  factionadmin:
    description: faction admin commands
    aliases: [fa]